language: php

php: 
  - '7.0'

env:
    global:
    - 'FTP_USER=sitimaeturoh'
    - 'FTP_PASS=06APRIL98'

script:
 - "curl -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com -Q 'mkd public_html/praktek_4D'"
 - "curl -T coba.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"